import type {
  AcademicEvent,
  AcademicMilestone,
  AuditEntry,
  DemoRoleDefinition,
  DemoRoleId,
  InstitutionCompliance,
  Programme,
  Semester,
  WorkspaceRole,
} from "./types";

export const academicYears = ["2026–27"] as const;
export const programmes: Programme[] = [
  "Four Year Undergraduate Programme (FYUGP)",
];
export const semesters: Semester[] = ["Semester 1", "Semester 3"];

export const roleDefinitions: Record<DemoRoleId, DemoRoleDefinition> = {
  public: {
    id: "public",
    label: "Public User",
    shortLabel: "Public calendar",
    description:
      "Explore the published statewide calendar without entering an institutional workspace.",
    identity: "Open access",
    destination: "/calendar",
    permissions: ["View published milestones", "Save local reminders"],
    navigation: [],
    accent: "slate",
  },
  university: {
    id: "university",
    label: "University Nodal Officer",
    shortLabel: "University Nodal Office",
    description:
      "Adopt the state calendar, confirm completion and submit justified change requests.",
    identity: "Sahya Higher Studies University",
    destination: "/university/dashboard",
    permissions: ["Confirm events", "Request date changes", "Coordinate colleges"],
    navigation: [
      { label: "University Dashboard", href: "/university/dashboard", icon: "dashboard" },
      { label: "Adopted Calendar", href: "/university/calendar", icon: "calendar" },
      {
        label: "Institution Structure",
        href: "/university/institution-structure",
        icon: "structure",
      },
      {
        label: "Calendar Submissions",
        href: "/university/calendar-submissions",
        icon: "publication",
      },
      {
        label: "Course Offerings",
        href: "/university/course-offerings",
        icon: "course",
      },
      {
        label: "Student Strength",
        href: "/university/student-strength",
        icon: "students",
      },
      { label: "Report Completion", href: "/university/completion", icon: "compliance" },
      { label: "Change Requests", href: "/university/change-requests", icon: "request" },
      { label: "Affiliated Colleges", href: "/university/colleges", icon: "institution" },
    ],
    accent: "teal",
  },
  monitoring: {
    id: "monitoring",
    label: "HEC Academic Monitoring Officer",
    shortLabel: "HEC Monitoring",
    description:
      "Monitor every institution, review compliance and screen incoming change requests.",
    identity: "Kerala Higher Education Council",
    destination: "/hec/dashboard",
    permissions: ["Statewide monitoring", "Compliance review", "Request screening"],
    navigation: [
      { label: "Command Centre", href: "/hec/dashboard", icon: "dashboard" },
      { label: "Compliance Matrix", href: "/hec/compliance", icon: "compliance" },
      { label: "Institution Registry", href: "/hec/institutions", icon: "institution" },
      {
        label: "Academic Years",
        href: "/hec/masters/academic-years",
        icon: "master",
      },
      {
        label: "Milestone Master",
        href: "/hec/masters/calendar-milestones",
        icon: "calendar",
      },
      {
        label: "Course Master",
        href: "/hec/masters/courses",
        icon: "course",
      },
      { label: "Admission Intake", href: "/hec/admissions", icon: "admission" },
      { label: "Vacancy Monitor", href: "/hec/vacancies", icon: "vacancy" },
      { label: "Change Requests", href: "/hec/requests", icon: "request" },
      { label: "Calendar Versions", href: "/hec/versions", icon: "version" },
      { label: "Reports", href: "/hec/reports", icon: "report" },
    ],
    accent: "navy",
  },
  committee: {
    id: "committee",
    label: "Empowered Committee Member",
    shortLabel: "Empowered Committee",
    description:
      "Review requests, inspect system-wide impact and record committee decisions.",
    identity: "Academic Calendar Empowered Committee",
    destination: "/workflow/dashboard",
    permissions: ["Review evidence", "Assess impact", "Approve or return"],
    navigation: [
      { label: "Review Queue", href: "/workflow/dashboard", icon: "request" },
      { label: "Meeting Agenda", href: "/workflow/agenda", icon: "agenda" },
      { label: "Decisions", href: "/workflow/decisions", icon: "decision" },
      { label: "Impact Review", href: "/workflow/impact", icon: "impact" },
    ],
    accent: "gold",
  },
  administrator: {
    id: "administrator",
    label: "HEC Calendar Administrator",
    shortLabel: "Calendar Administration",
    description:
      "Publish approved revisions, lock official versions and maintain the audit trail.",
    identity: "HEC Calendar Secretariat",
    destination: "/administrator/dashboard",
    permissions: ["Publish revisions", "Lock versions", "Maintain audit trail"],
    navigation: [
      {
        label: "Publication Desk",
        href: "/hec/publication",
        icon: "publication",
      },
      {
        label: "Approved Revisions",
        href: "/administrator/revisions",
        icon: "decision",
      },
      {
        label: "Calendar Versions",
        href: "/administrator/versions",
        icon: "version",
      },
      { label: "Audit Trail", href: "/audit", icon: "audit" },
    ],
    accent: "terracotta",
  },
  executive: {
    id: "executive",
    label: "Executive Viewer",
    shortLabel: "Executive View",
    description:
      "Read a concise academic pulse for senior council and government stakeholders.",
    identity: "Chairperson & senior leadership view",
    destination: "/executive/dashboard",
    permissions: ["Read statewide pulse", "Inspect critical alerts", "Export briefings"],
    navigation: [
      { label: "Academic Pulse", href: "/executive/dashboard", icon: "dashboard" },
      { label: "Critical Alerts", href: "/executive/alerts", icon: "alert" },
      {
        label: "Upcoming Milestones",
        href: "/executive/milestones",
        icon: "calendar",
      },
      { label: "Executive Reports", href: "/executive/reports", icon: "report" },
    ],
    accent: "green",
  },
};

export const workspaceRoles: WorkspaceRole[] = [
  "university",
  "monitoring",
  "committee",
  "administrator",
  "executive",
];

const programme: Programme = "Four Year Undergraduate Programme (FYUGP)";

export const academicMilestones: AcademicMilestone[] = [
  {
    id: "calendar-publication",
    title: "Calendar publication",
    councilBaselineDate: "2026-06-15",
    institutionScheduledDate: "2026-06-15",
    actualCompletionDate: "2026-06-15",
    eventType: "publication",
    programme,
    semester: "Semester 1",
    scope: "Statewide",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Master calendar version 1.0 published on the approved date.",
    version: "1.0",
    authorityReference: "KSHEC/ACAD/CAL/2026/01",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "admission-commencement",
    title: "Admission commencement",
    councilBaselineDate: "2026-06-22",
    institutionScheduledDate: "2026-06-22",
    actualCompletionDate: "2026-06-22",
    eventType: "admission",
    programme,
    semester: "Semester 1",
    scope: "All FYUGP admitting colleges",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Admissions opened across all participating institutions.",
    version: "1.0",
    authorityReference: "KSHEC/ADMN/2026/08",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "admission-closure",
    title: "Admission closure",
    councilBaselineDate: "2026-07-24",
    institutionScheduledDate: "2026-07-24",
    actualCompletionDate: "2026-07-24",
    eventType: "admission",
    programme,
    semester: "Semester 1",
    scope: "All FYUGP admitting colleges",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Institutional admission returns were closed on schedule.",
    version: "1.0",
    authorityReference: "KSHEC/ADMN/2026/19",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "classes-commence",
    title: "Semester classes commence",
    councilBaselineDate: "2026-08-03",
    institutionScheduledDate: "2026-08-03",
    actualCompletionDate: null,
    eventType: "instruction",
    programme,
    semester: "Semester 1",
    scope: "All first-semester cohorts",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Timetables and faculty allocation are confirmed.",
    version: "1.0",
    authorityReference: "KSHEC/ACAD/2026/24",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "course-registration",
    title: "Course registration deadline",
    councilBaselineDate: "2026-08-14",
    institutionScheduledDate: "2026-08-14",
    actualCompletionDate: null,
    eventType: "registration",
    programme,
    semester: "Semester 1",
    scope: "University registration portals",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "No reported variance from the statewide deadline.",
    version: "1.0",
    authorityReference: "KSHEC/FYUGP/2026/31",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "internal-assessment-1",
    title: "Internal Assessment 1",
    councilBaselineDate: "2026-09-21",
    institutionScheduledDate: "2026-09-21",
    actualCompletionDate: null,
    eventType: "assessment",
    programme,
    semester: "Semester 1",
    scope: "All FYUGP courses",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Assessment plans are aligned to the council window.",
    version: "1.0",
    authorityReference: "KSHEC/ASSESS/2026/07",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "student-feedback",
    title: "Student feedback window",
    councilBaselineDate: "2026-10-01",
    institutionScheduledDate: "2026-10-01",
    actualCompletionDate: null,
    eventType: "feedback",
    programme,
    semester: "Semester 3",
    scope: "University quality assurance cells",
    publicationStatus: "published",
    ragStatus: "grey",
    ragReason: "The reporting window has not yet opened.",
    version: "1.0",
    authorityReference: "KSHEC/IQAC/2026/12",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "exam-registration",
    title: "Examination registration",
    councilBaselineDate: "2026-10-12",
    institutionScheduledDate: "2026-10-12",
    actualCompletionDate: null,
    eventType: "registration",
    programme,
    semester: "Semester 1",
    scope: "University examination branches",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Registration window matches the approved baseline.",
    version: "1.0",
    authorityReference: "KSHEC/EXAM/2026/28",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "internal-assessment-2",
    title: "Internal Assessment 2",
    councilBaselineDate: "2026-10-19",
    institutionScheduledDate: "2026-10-21",
    actualCompletionDate: null,
    eventType: "assessment",
    programme,
    semester: "Semester 3",
    scope: "All third-semester cohorts",
    publicationStatus: "published",
    ragStatus: "amber",
    ragReason: "A two-day local variance is within the reporting tolerance.",
    version: "1.0",
    authorityReference: "KSHEC/ASSESS/2026/14",
    changeRequestStatus: "none",
    affectedCollegeCount: 42,
  },
  {
    id: "last-working-day",
    title: "Last working day",
    councilBaselineDate: "2026-11-13",
    institutionScheduledDate: "2026-11-13",
    actualCompletionDate: null,
    eventType: "instruction",
    programme,
    semester: "Semester 1",
    scope: "All participating institutions",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "The minimum instructional-day requirement remains achievable.",
    version: "1.0",
    authorityReference: "KSHEC/ACAD/2026/42",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "hall-ticket-publication",
    title: "Hall ticket publication",
    councilBaselineDate: "2026-11-23",
    institutionScheduledDate: "2026-11-23",
    actualCompletionDate: null,
    eventType: "publication",
    programme,
    semester: "Semester 1",
    scope: "Registered examination candidates",
    publicationStatus: "locked",
    ragStatus: "green",
    ragReason: "Candidate verification activities remain on schedule.",
    version: "1.0",
    authorityReference: "KSHEC/EXAM/2026/38",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "practical-examination",
    title: "Practical examination",
    councilBaselineDate: "2026-11-25",
    institutionScheduledDate: "2026-11-28",
    actualCompletionDate: null,
    eventType: "examination",
    programme,
    semester: "Semester 3",
    scope: "Laboratory and studio-based courses",
    publicationStatus: "published",
    ragStatus: "amber",
    ragReason: "Three-day variance is under routine monitoring.",
    version: "1.0",
    authorityReference: "KSHEC/EXAM/2026/40",
    changeRequestStatus: "screening",
    affectedCollegeCount: 31,
  },
  {
    id: "semester-1-theory-examination",
    title: "Semester 1 Theory Examination",
    councilBaselineDate: "2026-12-05",
    institutionScheduledDate: "2026-12-12",
    actualCompletionDate: null,
    eventType: "examination",
    programme,
    semester: "Semester 1",
    scope: "Sahya Higher Studies University",
    publicationStatus: "published",
    ragStatus: "red",
    ragReason:
      "Unauthorised +7 day deviation after severe monsoon disruption affected scheduled academic activities across 18 affiliated colleges.",
    version: "1.0",
    authorityReference: "SHSU/EXAM/CAL/2026/77",
    changeRequestStatus: "draft",
    affectedCollegeCount: 18,
  },
  {
    id: "centralised-valuation",
    title: "Centralised valuation",
    councilBaselineDate: "2026-12-19",
    institutionScheduledDate: "2026-12-26",
    actualCompletionDate: null,
    eventType: "valuation",
    programme,
    semester: "Semester 1",
    scope: "Sahya Higher Studies University",
    publicationStatus: "published",
    ragStatus: "amber",
    ragReason: "Dependent on the pending theory examination change request.",
    version: "1.0",
    authorityReference: "SHSU/EXAM/VAL/2026/11",
    changeRequestStatus: "draft",
    affectedCollegeCount: 18,
  },
  {
    id: "grade-approval",
    title: "Grade approval",
    councilBaselineDate: "2027-01-12",
    institutionScheduledDate: "2027-01-19",
    actualCompletionDate: null,
    eventType: "result",
    programme,
    semester: "Semester 1",
    scope: "University examination board",
    publicationStatus: "published",
    ragStatus: "grey",
    ragReason: "Downstream date will be reviewed after committee decision.",
    version: "1.0",
    authorityReference: "SHSU/EXAM/BOARD/2027/02",
    changeRequestStatus: "draft",
    affectedCollegeCount: 18,
  },
  {
    id: "result-publication",
    title: "Result publication",
    councilBaselineDate: "2027-01-20",
    institutionScheduledDate: "2027-01-27",
    actualCompletionDate: null,
    eventType: "result",
    programme,
    semester: "Semester 1",
    scope: "All Semester 1 candidates",
    publicationStatus: "published",
    ragStatus: "grey",
    ragReason: "Projected date pending approval of CR-2026-014.",
    version: "1.0",
    authorityReference: "SHSU/RESULT/2027/01",
    changeRequestStatus: "draft",
    affectedCollegeCount: 18,
  },
  {
    id: "supplementary-registration",
    title: "Supplementary examination registration",
    councilBaselineDate: "2027-02-01",
    institutionScheduledDate: "2027-02-01",
    actualCompletionDate: null,
    eventType: "registration",
    programme,
    semester: "Semester 3",
    scope: "Eligible supplementary candidates",
    publicationStatus: "published",
    ragStatus: "grey",
    ragReason: "The milestone is not yet due.",
    version: "1.0",
    authorityReference: "KSHEC/SUPP/2027/01",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
  {
    id: "supplementary-examination",
    title: "Supplementary examination",
    councilBaselineDate: "2027-03-08",
    institutionScheduledDate: "2027-03-08",
    actualCompletionDate: null,
    eventType: "examination",
    programme,
    semester: "Semester 3",
    scope: "Statewide supplementary examination window",
    publicationStatus: "published",
    ragStatus: "grey",
    ragReason: "The milestone is not yet due.",
    version: "1.0",
    authorityReference: "KSHEC/SUPP/2027/06",
    changeRequestStatus: "none",
    affectedCollegeCount: 186,
  },
];

export const centralIncident = academicMilestones.find(
  (event) => event.id === "semester-1-theory-examination",
)!;

export const statewideEvents: AcademicEvent[] = academicMilestones
  .filter((event) =>
    [
      "classes-commence",
      "course-registration",
      "internal-assessment-1",
      "exam-registration",
      "last-working-day",
      "practical-examination",
      "semester-1-theory-examination",
      "result-publication",
    ].includes(event.id),
  )
  .map((event) => ({
    id: event.id,
    title: event.title,
    category:
      event.eventType === "examination"
        ? "Examination"
        : event.eventType === "publication" || event.eventType === "registration"
          ? "Governance"
          : "Academic",
    start: event.councilBaselineDate,
    audience: event.scope,
    owner:
      event.scope === "Statewide"
        ? "HEC Calendar Secretariat"
        : "Academic Coordination Cell",
    status:
      event.ragStatus === "red"
        ? "overdue"
        : event.ragStatus === "amber"
          ? "attention"
          : event.ragStatus === "grey"
            ? "not-reported"
            : "on-track",
  }));

export const institutions: InstitutionCompliance[] = [
  {
    id: "sahya",
    name: "Sahya Higher Studies University",
    region: "Central",
    submission: "Change request draft in progress",
    variance: "+7 days · Theory examination",
    status: "overdue",
    colleges: [
      "Sahya College of Liberal Studies",
      "Nilgiri College of Applied Sciences",
      "Pamba Institute of Commerce",
    ],
  },
  {
    id: "vembanad",
    name: "Vembanad Academic University",
    region: "Central",
    submission: "Calendar adopted · 18 Jul",
    variance: "No material variance",
    status: "on-track",
    colleges: [
      "Vembanad College of Humanities",
      "Kumarakom School of Sciences",
      "Lakeview College of Management",
    ],
  },
  {
    id: "malabar",
    name: "Malabar Learning University",
    region: "North",
    submission: "Calendar adopted · 20 Jul",
    variance: "1 approved local date",
    status: "on-track",
    colleges: [
      "Beypore College of Arts",
      "Kallayi Institute of Technology",
      "Thalassery College of Social Sciences",
    ],
  },
  {
    id: "periyar",
    name: "Periyar Valley University",
    region: "Central",
    submission: "Awaiting syndicate confirmation",
    variance: "1 open clarification",
    status: "attention",
    colleges: [
      "Periyar College of Life Sciences",
      "Idukki School of Economics",
      "Valley College of Teacher Education",
    ],
  },
  {
    id: "ananthapuri",
    name: "Ananthapuri University of Studies",
    region: "South",
    submission: "Calendar adopted · 21 Jul",
    variance: "No material variance",
    status: "on-track",
    colleges: [
      "Ananthapuri College of Public Policy",
      "Neyyar College of Computing",
      "Kovalam School of Design",
    ],
  },
  {
    id: "kuttanad",
    name: "Kuttanad Knowledge University",
    region: "Central",
    submission: "Calendar review in progress",
    variance: "2 dates under monitoring",
    status: "attention",
    colleges: [
      "Kuttanad College of Environmental Studies",
      "Punnamada Institute of Commerce",
      "Alappuzha College of Languages",
    ],
  },
];

export const auditEntries: AuditEntry[] = [
  {
    id: "a1",
    action: "Master calendar published",
    actor: "Leela Krishnan · HEC Calendar Administrator",
    scope: "Academic year 2026–27",
    timestamp: "15 Jun 2026 · 10:42",
    detail: "Version 1.0 released and locked for participating universities.",
  },
  {
    id: "a2",
    action: "Theory examination variance detected",
    actor: "Academic Monitoring Cell",
    scope: "Sahya Higher Studies University",
    timestamp: "25 Jul 2026 · 16:18",
    detail: "A seven-day unauthorised deviation was flagged across 18 colleges.",
  },
  {
    id: "a3",
    action: "Change request draft opened",
    actor: "Prof. Anjali Menon · University Nodal Officer",
    scope: "CR-2026-014",
    timestamp: "26 Jul 2026 · 09:05",
    detail: "Monsoon disruption evidence is being assembled for university submission.",
  },
  {
    id: "a4",
    action: "Institutional impact note recorded",
    actor: "Sahya Academic Planning Office",
    scope: "18 affiliated colleges",
    timestamp: "26 Jul 2026 · 11:30",
    detail: "Downstream valuation, grade approval and result dates were identified.",
  },
];

export function getRoleDefinition(role: WorkspaceRole) {
  return roleDefinitions[role];
}
