import type {
  AcademicDeliveryUnit,
  AcademicYear,
  CalendarMilestoneDefinition,
  CourseMaster,
  CourseOffering,
  DemoSessionState,
  SemesterNumber,
  UniversityCalendarEntry,
  UniversityCalendarSubmission,
  UniversityProfile,
} from "./types";

export const domainAcademicYears: AcademicYear[] = [
  {
    id: "ay-2023-24",
    label: "2023–24",
    startDate: "2023-06-01",
    endDate: "2024-05-31",
    admissionYear: 2023,
    status: "closed",
  },
  {
    id: "ay-2024-25",
    label: "2024–25",
    startDate: "2024-06-01",
    endDate: "2025-05-31",
    admissionYear: 2024,
    status: "closed",
  },
  {
    id: "ay-2025-26",
    label: "2025–26",
    startDate: "2025-06-01",
    endDate: "2026-05-31",
    admissionYear: 2025,
    status: "closed",
  },
  {
    id: "ay-2026-27",
    label: "2026–27",
    startDate: "2026-06-01",
    endDate: "2027-05-31",
    admissionYear: 2026,
    status: "active",
  },
  {
    id: "ay-2027-28",
    label: "2027–28",
    startDate: "2027-06-01",
    endDate: "2028-05-31",
    admissionYear: 2027,
    status: "planned",
  },
];

const allSemesters: SemesterNumber[] = [1, 2, 3, 4, 5, 6, 7, 8];

export const domainCalendarMilestones: CalendarMilestoneDefinition[] = [
  {
    id: "cmd-admission-commencement",
    code: "ADMN-COMM-001",
    title: "Admission Commencement",
    description: "Official opening date for FYUGP admission activity.",
    category: "Admission",
    dateInputType: "single_date",
    applicableSemesters: [1],
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 10,
    active: true,
  },
  {
    id: "cmd-admission-closing",
    code: "ADMN-CLOSE-002",
    title: "Admission Closing",
    description: "Final deadline for completing the approved admission cycle.",
    category: "Admission",
    dateInputType: "deadline",
    applicableSemesters: [1],
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 20,
    active: true,
  },
  {
    id: "cmd-classes",
    code: "ACAD-CLS-003",
    title: "Semester Classes Commence",
    description: "Official commencement of semester instruction.",
    category: "Academic activity",
    dateInputType: "single_date",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 30,
    active: true,
  },
  {
    id: "cmd-registration",
    code: "ACAD-REG-004",
    title: "Course Registration Period",
    description: "Approved opening and closing window for course registration.",
    category: "Academic activity",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 40,
    active: true,
  },
  {
    id: "cmd-internal-1",
    code: "ASSESS-IA1-005",
    title: "Internal Assessment 1",
    description: "First common internal assessment window.",
    category: "Assessment",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 2,
    toleranceAfterDays: 2,
    mandatory: true,
    displayOrder: 50,
    active: true,
  },
  {
    id: "cmd-internal-2",
    code: "ASSESS-IA2-006",
    title: "Internal Assessment 2",
    description: "Second common internal assessment window.",
    category: "Assessment",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 2,
    toleranceAfterDays: 2,
    mandatory: true,
    displayOrder: 60,
    active: true,
  },
  {
    id: "cmd-feedback",
    code: "ACAD-FDBK-007",
    title: "Student Feedback Period",
    description: "Approved window for structured semester feedback collection.",
    category: "Academic activity",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 2,
    toleranceAfterDays: 2,
    mandatory: false,
    displayOrder: 70,
    active: true,
  },
  {
    id: "cmd-last-working-day",
    code: "ACAD-LWD-008",
    title: "Last Working Day",
    description: "Official closure of scheduled semester instruction.",
    category: "Academic activity",
    dateInputType: "single_date",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 80,
    active: true,
  },
  {
    id: "cmd-exam-registration",
    code: "EXAM-REG-009",
    title: "Examination Registration Deadline",
    description: "Last approved date for university examination registration.",
    category: "Examination",
    dateInputType: "deadline",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 90,
    active: true,
  },
  {
    id: "cmd-hall-ticket",
    code: "EXAM-HALL-010",
    title: "Hall Ticket Publication",
    description: "Deadline for publishing examination admission tickets.",
    category: "Examination",
    dateInputType: "deadline",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "exact_date",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 100,
    active: true,
  },
  {
    id: "cmd-practical",
    code: "EXAM-PRAC-011",
    title: "Practical Examination Period",
    description: "Approved window for laboratory, studio and field examinations.",
    category: "Examination",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 3,
    mandatory: true,
    displayOrder: 110,
    active: true,
  },
  {
    id: "cmd-theory",
    code: "EXAM-THEORY-012",
    title: "Theory Examination Period",
    description: "Official start and end of the common theory examination window.",
    category: "Examination",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 120,
    active: true,
  },
  {
    id: "cmd-valuation",
    code: "EXAM-VAL-013",
    title: "Centralised Valuation Period",
    description: "Approved start and end dates for centralised valuation.",
    category: "Valuation",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 2,
    mandatory: true,
    displayOrder: 130,
    active: true,
  },
  {
    id: "cmd-grade-approval",
    code: "RESULT-GRADE-014",
    title: "Grade Approval",
    description: "Deadline for the university grade-approval process.",
    category: "Result",
    dateInputType: "deadline",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "reporting_only",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 140,
    active: true,
  },
  {
    id: "cmd-results",
    code: "RESULT-PUB-015",
    title: "Result Publication",
    description: "Statewide result publication and reporting deadline.",
    category: "Result",
    dateInputType: "deadline",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate"],
    alignmentRule: "reporting_only",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 0,
    mandatory: true,
    displayOrder: 150,
    active: true,
  },
  {
    id: "cmd-supp-registration",
    code: "SUPP-REG-016",
    title: "Supplementary Examination Registration",
    description: "Registration deadline for the supplementary examination cycle.",
    category: "Examination",
    dateInputType: "deadline",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 2,
    mandatory: false,
    displayOrder: 160,
    active: true,
  },
  {
    id: "cmd-supp-exam",
    code: "SUPP-EXAM-017",
    title: "Supplementary Examination Period",
    description: "Approved window for supplementary examinations.",
    category: "Examination",
    dateInputType: "date_range",
    applicableSemesters: allSemesters,
    applicableProgrammeTypes: ["FYUGP", "Undergraduate", "Vocational"],
    alignmentRule: "permitted_window",
    toleranceBeforeDays: 0,
    toleranceAfterDays: 3,
    mandatory: false,
    displayOrder: 170,
    active: true,
  },
];

export const domainCourseMasters: CourseMaster[] = [
  ["cm-ba-eng", "HEC-UG-ENG-001", "B.A. English", "BA English", "Humanities", "Undergraduate", 4, 8],
  ["cm-ba-eco", "HEC-UG-ECO-002", "B.A. Economics", "BA Economics", "Social Sciences", "Undergraduate", 4, 8],
  ["cm-bcom", "HEC-UG-COM-003", "B.Com.", "B.Com.", "Commerce", "Undergraduate", 4, 8],
  ["cm-bcom-fin", "HEC-UG-COM-004", "B.Com. Finance", "B.Com. Finance", "Commerce", "Undergraduate", 4, 8],
  ["cm-bsc-cs", "HEC-UG-CS-005", "B.Sc. Computer Science", "BSc Computer Science", "Computer Science", "Undergraduate", 4, 8],
  ["cm-bsc-math", "HEC-UG-MAT-006", "B.Sc. Mathematics", "BSc Mathematics", "Mathematics", "Undergraduate", 4, 8],
  ["cm-bsc-physics", "HEC-UG-PHY-007", "B.Sc. Physics", "BSc Physics", "Physical Sciences", "Undergraduate", 4, 8],
  ["cm-bsc-chem", "HEC-UG-CHE-008", "B.Sc. Chemistry", "BSc Chemistry", "Chemical Sciences", "Undergraduate", 4, 8],
  ["cm-bsc-psych", "HEC-UG-PSY-009", "B.Sc. Psychology", "BSc Psychology", "Behavioural Sciences", "Undergraduate", 4, 8],
  ["cm-bba", "HEC-UG-MGT-010", "Bachelor of Business Administration", "BBA", "Management", "Undergraduate", 4, 8],
  ["cm-bsw", "HEC-UG-SWK-011", "Bachelor of Social Work", "BSW", "Social Work", "Undergraduate", 4, 8],
  ["cm-bvoc-media", "HEC-UG-VOC-012", "B.Voc. Digital Media", "B.Voc. Digital Media", "Digital Media", "Vocational", 3, 6],
].map(
  ([
    id,
    courseCode,
    courseName,
    shortName,
    discipline,
    programmeType,
    durationYears,
    totalSemesters,
  ]) => ({
    id: id as string,
    courseCode: courseCode as string,
    courseName: courseName as string,
    shortName: shortName as string,
    qualificationLevel: "Undergraduate",
    discipline: discipline as string,
    programmeType: programmeType as CourseMaster["programmeType"],
    durationYears: durationYears as number,
    totalSemesters: totalSemesters as SemesterNumber,
    active: true,
    effectiveFromAcademicYear: "ay-2026-27",
    description: `${courseName} is an illustrative active HEC Course Master record for the prototype.`,
  }),
);

export const domainUniversityProfiles: UniversityProfile[] = [
  {
    id: "sahya",
    name: "Sahya Higher Studies University",
    shortName: "Sahya University",
    operatingModel: "hybrid",
    district: "Thrissur",
    active: true,
  },
  {
    id: "vembanad",
    name: "Vembanad Academic University",
    shortName: "Vembanad University",
    operatingModel: "affiliating",
    district: "Kottayam",
    active: true,
  },
  {
    id: "malabar",
    name: "Malabar Learning University",
    shortName: "Malabar University",
    operatingModel: "affiliating",
    district: "Kozhikode",
    active: true,
  },
  {
    id: "periyar",
    name: "Periyar Valley University",
    shortName: "Periyar Valley",
    operatingModel: "hybrid",
    district: "Idukki",
    active: true,
  },
  {
    id: "ananthapuri",
    name: "Ananthapuri University of Studies",
    shortName: "Ananthapuri University",
    operatingModel: "teaching_only",
    district: "Thiruvananthapuram",
    active: true,
  },
  {
    id: "kuttanad",
    name: "Kuttanad Knowledge University",
    shortName: "Kuttanad University",
    operatingModel: "affiliating",
    district: "Alappuzha",
    active: true,
  },
];

export const domainAcademicDeliveryUnits: AcademicDeliveryUnit[] = [
  ["du-sahya-campus", "sahya", "Sahya University Teaching Campus", "Sahya Campus", "university_campus", "Thrissur", "SHSU-CAMP-01", "ay-2023-24"],
  ["du-sahya-humanities", "sahya", "School of Humanities", "Humanities School", "university_department", "Thrissur", "SHSU-DEPT-01", "ay-2024-25"],
  ["du-sahya-science", "sahya", "School of Science and Technology", "Science & Technology", "university_department", "Thrissur", "SHSU-DEPT-02", "ay-2024-25"],
  ["du-sahya-liberal", "sahya", "Sahya College of Liberal Studies", "Sahya Liberal", "affiliated_college", "Thrissur", "SHSU-AFF-01", "ay-2023-24"],
  ["du-sahya-nilgiri", "sahya", "Green Valley College", "Green Valley", "affiliated_college", "Palakkad", "SHSU-AFF-02", "ay-2024-25"],
  ["du-sahya-pamba", "sahya", "Pamba Institute of Commerce", "Pamba Commerce", "affiliated_college", "Pathanamthitta", "SHSU-AFF-03", "ay-2024-25"],
  ["du-anan-campus", "ananthapuri", "University Teaching Campus", "Ananthapuri Campus", "university_campus", "Thiruvananthapuram", "AUS-CAMP-01", "ay-2023-24"],
  ["du-anan-humanities", "ananthapuri", "School of Languages", "Languages School", "university_department", "Thiruvananthapuram", "AUS-DEPT-01", "ay-2023-24"],
  ["du-anan-sciences", "ananthapuri", "School of Computing", "Computing School", "university_department", "Thiruvananthapuram", "AUS-DEPT-02", "ay-2024-25"],
  ["du-anan-social", "ananthapuri", "School of Social Sciences", "Social Sciences School", "university_department", "Thiruvananthapuram", "AUS-DEPT-03", "ay-2024-25"],
  ["du-vemb-humanities", "vembanad", "Vembanad College of Humanities", "Vembanad Humanities", "affiliated_college", "Kottayam", "VAU-AFF-01", "ay-2023-24"],
  ["du-vemb-kumarakom", "vembanad", "Kumarakom School of Sciences", "Kumarakom Sciences", "affiliated_college", "Kottayam", "VAU-AFF-02", "ay-2024-25"],
  ["du-vemb-lakeview", "vembanad", "Lakeview College of Management", "Lakeview Management", "affiliated_college", "Alappuzha", "VAU-AFF-03", "ay-2024-25"],
  ["du-malabar-beypore", "malabar", "Beypore College of Arts", "Beypore Arts", "affiliated_college", "Kozhikode", "MLU-AFF-01", "ay-2023-24"],
  ["du-malabar-kallayi", "malabar", "Kallayi Institute of Technology", "Kallayi Institute", "affiliated_college", "Kozhikode", "MLU-AFF-02", "ay-2024-25"],
  ["du-periyar-centre", "periyar", "Periyar Centre for Applied Learning", "Periyar Centre", "university_centre", "Idukki", "PVU-CENTRE-01", "ay-2023-24"],
  ["du-periyar-idukki", "periyar", "Idukki School of Economics and Science", "Idukki School", "constituent_college", "Idukki", "PVU-CONST-01", "ay-2024-25"],
  ["du-kuttanad-env", "kuttanad", "Kuttanad College of Environmental Studies", "Kuttanad Environmental", "affiliated_college", "Alappuzha", "KKU-AFF-01", "ay-2024-25"],
].map(([id, universityId, name, shortName, unitType, district, institutionCode, teachingCommencedAcademicYearId]) => ({
  id: id as string,
  universityId: universityId as string,
  name: name as string,
  shortName: shortName as string,
  unitType: unitType as AcademicDeliveryUnit["unitType"],
  district: district as string,
  institutionCode: institutionCode as string,
  active: true,
  teachingCommencedAcademicYearId:
    teachingCommencedAcademicYearId as string,
}));

type OfferingBlueprint = {
  id: string;
  universityId: string;
  deliveryUnitId: string;
  courseMasterId: string;
  status?: CourseOffering["offeringStatus"];
  shift?: CourseOffering["shift"];
};

const offeringBlueprints: OfferingBlueprint[] = [
  { id: "off-001", universityId: "sahya", deliveryUnitId: "du-sahya-science", courseMasterId: "cm-bsc-cs" },
  { id: "off-002", universityId: "sahya", deliveryUnitId: "du-sahya-humanities", courseMasterId: "cm-ba-eco" },
  { id: "off-003", universityId: "sahya", deliveryUnitId: "du-sahya-liberal", courseMasterId: "cm-ba-eng" },
  { id: "off-004", universityId: "sahya", deliveryUnitId: "du-sahya-liberal", courseMasterId: "cm-bcom" },
  { id: "off-005", universityId: "sahya", deliveryUnitId: "du-sahya-nilgiri", courseMasterId: "cm-bsc-cs" },
  { id: "off-006", universityId: "sahya", deliveryUnitId: "du-sahya-nilgiri", courseMasterId: "cm-bsc-math" },
  { id: "off-007", universityId: "sahya", deliveryUnitId: "du-sahya-pamba", courseMasterId: "cm-bcom-fin" },
  { id: "off-008", universityId: "sahya", deliveryUnitId: "du-sahya-pamba", courseMasterId: "cm-bba", shift: "evening" },
  { id: "off-009", universityId: "ananthapuri", deliveryUnitId: "du-anan-campus", courseMasterId: "cm-ba-eng", status: "submitted" },
  { id: "off-010", universityId: "ananthapuri", deliveryUnitId: "du-anan-campus", courseMasterId: "cm-bsc-psych" },
  { id: "off-011", universityId: "ananthapuri", deliveryUnitId: "du-anan-humanities", courseMasterId: "cm-ba-eco" },
  { id: "off-012", universityId: "ananthapuri", deliveryUnitId: "du-anan-social", courseMasterId: "cm-bsw" },
  { id: "off-013", universityId: "ananthapuri", deliveryUnitId: "du-anan-sciences", courseMasterId: "cm-bsc-physics" },
  { id: "off-014", universityId: "ananthapuri", deliveryUnitId: "du-anan-sciences", courseMasterId: "cm-bsc-chem" },
  { id: "off-015", universityId: "vembanad", deliveryUnitId: "du-vemb-humanities", courseMasterId: "cm-ba-eng" },
  { id: "off-016", universityId: "vembanad", deliveryUnitId: "du-vemb-humanities", courseMasterId: "cm-bcom" },
  { id: "off-017", universityId: "vembanad", deliveryUnitId: "du-vemb-kumarakom", courseMasterId: "cm-bsc-cs" },
  { id: "off-018", universityId: "vembanad", deliveryUnitId: "du-vemb-kumarakom", courseMasterId: "cm-bsc-math" },
  { id: "off-019", universityId: "vembanad", deliveryUnitId: "du-vemb-lakeview", courseMasterId: "cm-bba" },
  { id: "off-020", universityId: "vembanad", deliveryUnitId: "du-vemb-lakeview", courseMasterId: "cm-bcom-fin", shift: "evening" },
  { id: "off-021", universityId: "malabar", deliveryUnitId: "du-malabar-beypore", courseMasterId: "cm-bsw" },
  { id: "off-022", universityId: "malabar", deliveryUnitId: "du-malabar-kallayi", courseMasterId: "cm-bvoc-media" },
  { id: "off-023", universityId: "periyar", deliveryUnitId: "du-periyar-centre", courseMasterId: "cm-bsc-psych" },
  { id: "off-024", universityId: "periyar", deliveryUnitId: "du-periyar-idukki", courseMasterId: "cm-bsc-physics" },
  { id: "off-025", universityId: "kuttanad", deliveryUnitId: "du-kuttanad-env", courseMasterId: "cm-bsc-chem", status: "draft" },
  { id: "off-026", universityId: "sahya", deliveryUnitId: "du-sahya-campus", courseMasterId: "cm-bsc-physics", status: "submitted" },
  { id: "off-027", universityId: "ananthapuri", deliveryUnitId: "du-anan-sciences", courseMasterId: "cm-bsc-cs" },
];

export const domainCourseOfferings: CourseOffering[] = offeringBlueprints.map(
  (offering, index) => ({
    id: offering.id,
    academicYearId: "ay-2026-27",
    universityId: offering.universityId,
    deliveryUnitId: offering.deliveryUnitId,
    courseMasterId: offering.courseMasterId,
    offeringStatus: offering.status ?? "verified",
    mode: index === 21 ? "blended" : "in_person",
    shift: offering.shift ?? "day",
    approvalReference:
      offering.id === "off-009" || offering.id === "off-025"
        ? ""
        : `HEC/OFFER/2026/${String(index + 1).padStart(3, "0")}`,
    effectiveFrom: "2026-06-01",
    effectiveTo: null,
    reviewNote:
      offering.id === "off-009"
        ? "Approval reference must be supplied before HEC verification."
        : "",
    lastUpdatedAt: "2026-07-26T12:30:00.000Z",
  }),
);

export const domainCalendarSubmissions: UniversityCalendarSubmission[] = [
  ["cal-sub-sahya-26", "sahya", "1.0", "locked", "all_delivery_units"],
  ["cal-sub-vembanad-26", "vembanad", "1.0", "accepted", "all_delivery_units"],
  ["cal-sub-malabar-26", "malabar", "1.0", "accepted", "all_delivery_units"],
  ["cal-sub-periyar-26", "periyar", "0.9", "under_review", "selected_delivery_units"],
  ["cal-sub-anan-26", "ananthapuri", "1.0", "accepted", "university_teaching_only"],
  ["cal-sub-kuttanad-26", "kuttanad", "0.8", "submitted", "all_delivery_units"],
].map(([id, universityId, version, status, scopeType]) => ({
  id: id as string,
  universityId: universityId as string,
  academicYearId: "ay-2026-27",
  programmeType: "FYUGP",
  title: "FYUGP Annual Academic Calendar 2026–27",
  version: version as string,
  applicableSemesters: [1, 3],
  status: status as UniversityCalendarSubmission["status"],
  scopeType: scopeType as UniversityCalendarSubmission["scopeType"],
  selectedDeliveryUnitIds:
    scopeType === "selected_delivery_units"
      ? ["du-periyar-centre", "du-periyar-idukki"]
      : [],
  createdAt: "2026-07-14T09:15:00.000Z",
  submittedAt: "2026-07-18T10:00:00.000Z",
  reviewedAt:
    status === "accepted" || status === "locked"
      ? "2026-07-21T15:30:00.000Z"
      : null,
  lockedAt: status === "locked" ? "2026-07-22T09:00:00.000Z" : null,
  reviewNote:
    status === "locked"
      ? "Accepted against the published FYUGP milestone definitions and locked for implementation."
      : "",
  declarationAccepted: true,
}));

export const domainCalendarBaselineDates: Record<
  string,
  { start: string; end: string | null }
> = {
  "cmd-admission-commencement": { start: "2026-06-22", end: null },
  "cmd-admission-closing": { start: "2026-07-24", end: null },
  "cmd-classes": { start: "2026-08-03", end: null },
  "cmd-registration": { start: "2026-08-03", end: "2026-08-14" },
  "cmd-internal-1": { start: "2026-09-21", end: "2026-09-25" },
  "cmd-internal-2": { start: "2026-10-19", end: "2026-10-23" },
  "cmd-feedback": { start: "2026-10-26", end: "2026-10-30" },
  "cmd-last-working-day": { start: "2026-11-13", end: null },
  "cmd-exam-registration": { start: "2026-11-06", end: null },
  "cmd-hall-ticket": { start: "2026-11-20", end: null },
  "cmd-practical": { start: "2026-11-25", end: "2026-12-02" },
  "cmd-theory": { start: "2026-12-05", end: "2026-12-16" },
  "cmd-valuation": { start: "2026-12-19", end: "2027-01-08" },
  "cmd-grade-approval": { start: "2027-01-16", end: null },
  "cmd-results": { start: "2027-01-20", end: null },
  "cmd-supp-registration": { start: "2027-02-08", end: null },
  "cmd-supp-exam": { start: "2027-03-01", end: "2027-03-06" },
};

export const domainCalendarEntries: UniversityCalendarEntry[] =
  domainCalendarSubmissions.flatMap((submission) =>
    domainCalendarMilestones.map((milestone) => {
      const baseline = domainCalendarBaselineDates[milestone.id];
      const sahyaTheory =
        submission.universityId === "sahya" && milestone.id === "cmd-theory";
      return {
        id: `entry-${submission.universityId}-${milestone.id}`,
        submissionId: submission.id,
        milestoneDefinitionId: milestone.id,
        semester: 1,
        councilBaselineStartDate: baseline.start,
        councilBaselineEndDate: baseline.end,
        universityStartDate: sahyaTheory ? "2026-12-12" : baseline.start,
        universityEndDate: baseline.end,
        actualStartDate: null,
        actualEndDate: null,
        varianceDays: sahyaTheory ? 7 : 0,
        ragStatus: sahyaTheory ? "red" : "green",
        ragReason: sahyaTheory
          ? "Unauthorised seven-day examination deviation; CR-2026-014 remains in draft in the initial scenario."
          : milestone.alignmentRule === "reporting_only"
            ? "Reporting milestone recorded against the Council calendar."
            : "University date aligns with the approved Council baseline.",
        deviationReason: sahyaTheory
          ? "Severe monsoon disruption affected scheduled academic activities across 18 affiliated colleges."
          : "",
        evidenceStatus: sahyaTheory ? "pending" : "not_required",
        changeRequestId: sahyaTheory ? "CR-2026-014" : null,
      };
    }),
  );

export const defaultDomainState: Pick<
  DemoSessionState,
  | "academicYears"
  | "calendarMilestoneDefinitions"
  | "courseMasters"
  | "universityProfiles"
  | "academicDeliveryUnits"
  | "universityCalendarSubmissions"
  | "universityCalendarEntries"
  | "courseOfferings"
> = {
  academicYears: domainAcademicYears,
  calendarMilestoneDefinitions: domainCalendarMilestones,
  courseMasters: domainCourseMasters,
  universityProfiles: domainUniversityProfiles,
  academicDeliveryUnits: domainAcademicDeliveryUnits,
  universityCalendarSubmissions: domainCalendarSubmissions,
  universityCalendarEntries: domainCalendarEntries,
  courseOfferings: domainCourseOfferings,
};
